In [1]:
import torch

In [3]:
t1 = torch.rand(2, 5)
t2 = torch.rand(1, 5)

t1 + t2

tensor([[0.5648, 0.7022, 0.9566, 1.4914, 0.9871],
        [0.3255, 0.4380, 1.5922, 0.8207, 1.0893]])

In [4]:
t1

tensor([[0.4676, 0.3826, 0.0375, 0.7452, 0.3461],
        [0.2283, 0.1185, 0.6731, 0.0746, 0.4483]])

In [5]:
t2

tensor([[0.0972, 0.3196, 0.9191, 0.7461, 0.6410]])